title: Magliette di Calcio
author: 
  name: Collezione Magliette
  email: 

description: >-
  Collezione di magliette di calcio storiche

baseurl: "/sito-fede"
url: "https://riccardoBuso5.github.io"

github_username: riccardoBuso5

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

exclude:
  - .jekyll-cache/
  - .gitignore
  - Gemfile
  - Gemfile.lock
